# @package _global_

defaults:
  - /full_feature_search
  - _self_

comet_ml: true
device: cuda
jax_jit_cache_dir: "$HOME/scratch/jax_cache"

model:
  use_bias: false
  n_frozen_layers: 0
  hidden_dim: 5120
  weight_init_method: lecun_uniform

task:
  distractor_chance: 0.0
  noise_std: 0.0
  n_stationary_layers: 0
  flip_rate: ${eval:2**-12}
  n_features: 10
  hidden_dim: 10

feature_recycling:
  recycle_rate: 0.0
  use_cbp_utility: true
  utility_decay: 0.99
  feature_protection_steps: 0
  incoming_weight_init: lecun_uniform
  prune_frequency: 4

train:
  total_steps: 10_000_000
  standardize_cumulants: false

  # Logging parameters
  log_freq: 10000
  log_utility_stats: false
  log_pruning_stats: false
  log_model_stats: false
  log_optimizer_stats: false
  log_feature_match_stats: true

optimizer:
  name: idbd
  version: squared_grads
  autostep: true
  learning_rate: ${eval:0.03 / ${model.hidden_dim} ** 0.75}
  meta_learning_rate: 0.005

representation_optimizer:
  name: null # {null, sgd, sgd_momentum, rmsprop, adam, idbd}
  weight_decay: 0
  learning_rate: 0.1