defaults:
- full_feature_search
- _self_

wandb: true
comet_ml: false

device: cuda

model:
  hidden_dim: 20_000
  n_frozen_layers: 0

task:
  distractor_chance: 0.0
  noise_std: 0.0
  distractor_mean_range: [ 0.0, 0.0 ]

feature_recycling:
  recycle_rate: 0.005
  use_signed_utility: False
  initial_step_size_method: mean
  prune_frequency: 1

train:
  total_steps: 200_000
  log_freq: 2_000
  standardize_cumulants: true

optimizer:
  name: idbd
  learning_rate: ${eval:0.03 / ${model.hidden_dim} ** 0.75}
  version: squared_grads
  weight_decay: 0.0
  autostep: true
  step_size_decay: 0.0


seed: 20250827
