defaults:
- full_feature_search
- summation_task
- _self_

wandb: true

task:
  change_subset_freq: 200
  flip_multiplier_freq: null

feature_recycling:
  recycle_rate: 0.0

model:
  n_layers: 3
  hidden_dim: 300
  activation: linear
  use_bias: false
  n_frozen_layers: 0

train:
  total_steps: 1_000_000
  log_freq: 500
  log_optimizer_stats: false
  log_update_stats: false

# optimizer:
#   name: sgd
#   learning_rate: 0.001

# optimizer:
#   name: idbd
#   autostep: true
#   learning_rate: 0.0001
#   meta_learning_rate: 0.01

optimizer:
  name: upgd
  learning_rate: 0.001
  beta_utility: 0.99
  sigma: 0.001
  weight_decay: 0.001

seed: [26011701, 26011702, 26011703, 26011704, 26011705]


