defaults:
- ensemble_feature_search
- _self_

wandb: false
comet_ml: false

device: cuda

model:
  hidden_dim: 20_480 # 20_480
  ensemble_dim: 512 # 512
  n_ensemble_members: 40 # 40
  prediction_mode: best_ensemble # {mean, mean_top_half, median, median_top_half, best_ensemble}
  feature_utility_mode: best # {mean, median, best}
  ensemble_utility_mode: objective_improvement # {objective_improvement, negative_loss}
  ensemble_feature_selection_method: random # {random, inverse_frequency}

task:
  distractor_chance: 0.0
  noise_std: 0.0

feature_recycling:
  recycle_rate: 0.005
  ensemble_recycle_rate: 0.0 # 0.005

train:
  total_steps: 800 # 200_000
  standardize_cumulants: true

optimizer:
  name: idbd
  learning_rate: ${eval:0.03 / ${model.ensemble_dim} ** 0.75} # 0.0001
  version: squared_grads
  autostep: true


seed: 200
