defaults:
- full_feature_search
- _self_

wandb: false
comet_ml: false

device: cpu

model:
  hidden_dim: 1240

task:
  distractor_chance: 0.0
  noise_std: 0.4
  distractor_mean_range: [ 0.0, 0.0 ]

feature_recycling:
  recycle_rate: 0.005
  use_signed_utility: False
  initial_step_size_method: mean

train:
  total_steps: 200_000
  standardize_cumulants: true

optimizer:
  name: idbd
  learning_rate: 1.0 # ${eval:0.03 / ${model.hidden_dim} ** 0.75}
  version: squared_grads
  weight_decay: 0.0
  autostep: false # true
  step_size_decay: 0.0


seed: 20250827
