defaults:
- comet_sweeps/paper_draft_v2_part_1/base_config
- _self_

wandb: true

model:
  hidden_dim: 5120
  use_bias: false

task:
  flip_rate: "${eval:2**-12}"

feature_recycling:
  recycle_rate: 0.001
  utility_decay: 0.999
  utility_reset_mode: median
  feature_protection_steps: 0
  initial_step_size_method: median

train:
  log_model_stats: true
  log_optimizer_stats: true
  standardize_cumulants: false
  total_steps: 30000000

optimizer:
  learning_rate: "${eval:2**-14}"
  meta_learning_rate: "${eval:2**-5}"

seed: 702

