defaults:
- full_feature_search
- _self_

wandb: true
comet_ml: false

device: cpu

model:
  hidden_dim: 1024

task:
  distractor_chance: 0.0
  noise_std: 0.0
  distractor_mean_range: [ 0.0, 0.0 ]

feature_recycling:
  recycle_rate: 0.005
  use_signed_utility: False

train:
  total_steps: 200_000
  standardize_cumulants: true

optimizer:
  name: idbd
  learning_rate: ${eval:0.03 / ${model.hidden_dim} ** 0.75}
  version: squared_grads
  weight_decay: 0.001
  autostep: true


seed: 20250819
