defaults:
  - _self_

seed: null
wandb: false
project: feature-recycling
device: cuda

# Task parameters
task:
  name: linear_geoff # dummy, static_linear_geoff, linear_geoff
  type: regression # classification, regression
  n_features: 20
  n_real_features: 10

# Input recycling parameters
input_recycling:
  use_cbp_utility: false
  distractor_chance: 0.5
  recycle_rate: 0.1
  utility_decay: 0.99
  feature_protection_steps: 100
  n_start_real_features: -1

# Feature recycling parameters
feature_recycling:
  use_cbp_utility: false
  recycle_rate: 0.0001
  utility_decay: 0.99
  feature_protection_steps: 100

# Train parameters
train:
  optimizer: adam # adam, idbd, partial_idbd
  weight_decay: 0
  batch_size: 1
  learning_rate: 0.001
  total_steps: 10000
  log_freq: 100
  standardize_cumulants: false

# Model parameters
model:
  weight_init_method: zeros # zeros, kaiming_uniform
  n_layers: 1
  hidden_dim: 256
  output_dim: 10
  activation: relu
  n_frozen_layers: 0

# IDBD parameters
idbd:
  meta_learning_rate: 0.01
  version: squared_inputs # squared_inputs, squared_grads, hvp, hessian_diagonal
  autostep: false