defaults:
  - full_feature_search
  - _self_

model:
  hidden_dim: 41
  use_bias: false

feature_recycling:
  recycle_rate: 0.005
  freeze_perfect_features: true

train:
  standardize_cumulants: false
  log_feature_match_stats: true

optimizer:
  name: idbd # {idbd, adam, rmsprop, sgd}
  learning_rate: 0.00001 # Initial step-size for idbd

seed: 20251107