defaults:
  - full_feature_search
  - _self_

model:
  hidden_dim: 20
  use_bias: false
  use_perfect_features: true

feature_recycling:
  recycle_rate: 0.0
  perfect_features_irreplaceable: false

train:
  standardize_cumulants: false
  log_model_stats: false
  log_feature_matched_optimizer_stats: false
  log_feature_match_stats: true

optimizer:
  name: idbd # {idbd, adam, rmsprop, sgd}
  learning_rate: 0.00001 # Initial step-size for idbd

seed: 20251107