defaults:
- core_transient_binary
- _self_

wandb: false

task:
  n_outputs: 20

  n_core_layers: 1
  n_transient_layers: 2
  transient_sparsity: 0.9
  transient_activation_rate: 0.05
  input_change_freq: 100_000

model:
  n_layers: 4
  hidden_dim: 256
  activation: ltu
  use_bias: false
  n_frozen_layers: 1
  use_perfect_features: true

train:
  total_steps: 5_000_000
  log_freq: 2000

feature_recycling:
  recycle_rate: 0.0
  perfect_features_irreplaceable: true

optimizer:
  name: idbd
  autostep: true
  learning_rate: 8.0
  meta_learning_rate: 0.05

seed: 2601091

