# @package _global_

defaults:
  - /full_feature_search
  - _self_

comet_ml: true
device: cuda
jax_jit_cache_dir: ${oc.env:HOME}/scratch/jax_cache

model:
  use_bias: true
  n_frozen_layers: 1

task:
  distractor_chance: 0.0
  noise_std: 0.0
  n_stationary_layers: 1

feature_recycling:
  use_cbp_utility: true
  recycle_rate: 0.005
  utility_decay: 0.99
  feature_protection_steps: 0
  prune_frequency: 4

train:
  total_steps: 3_000_000
  standardize_cumulants: true

  # Logging parameters
  log_freq: 10000
  log_utility_stats: false
  log_pruning_stats: false
  log_model_stats: false
  log_feature_match_stats: true

optimizer:
  name: idbd
  version: prediction_grads
  autostep: true
  learning_rate: ${eval:0.03 / ${model.hidden_dim} ** 0.75}
  meta_learning_rate: 0.005

representation_optimizer:
  name: null # {null, sgd, sgd_momentum, rmsprop, adam, idbd}
  weight_decay: 0
  learning_rate: 0.1