defaults:
  - nonlinear_geoff

wandb: false
seed: 20
device: cuda

model:
  activation: relu
  hidden_dim: 50
  n_layers: 3
  weight_init_method: kaiming_uniform

task:
  activation: ltu
  flip_rate: 0
  hidden_dim: 100
  n_features: 100
  n_layers: 3
  n_real_features: 100
  sparsity: 0.98
  weight_init: binary
  weight_scale: 1

train:
  batch_size: 3
  learning_rate: 0.005
  log_freq: 100
  optimizer: adam
  standardize_cumulants: true
  total_steps: 50000

input_recycling:
  use_cbp_utility: false
  distractor_chance: 0
  recycle_rate: 0

feature_recycling:
  use_cbp_utility: true
  recycle_rate: 0.0001
  utility_decay: 0.99
  feature_protection_steps: 100


# TODO:
#   - Change how CBP handles resetting otpimzier states
#   - Log number of features recycled
#   - Step through everything to make sure it's working as expected