# @package _global_

defaults:
- /full_feature_search
- _self_

comet_ml: true
device: cpu

task:
  hidden_dim: 10
  n_features: 10
  n_real_features: 10
  n_layers: 2
  noise_std: 0.0
  distractor_chance: 0.0

feature_recycling:
  use_cbp_utility: true
  utility_decay: 0.99
  recycle_rate: 0.005
  feature_protection_steps: 0

train:
  total_steps: 1_000_000
  optimizer: idbd
  standardize_cumulants: true
  learning_rate: ${eval:0.03 / ${model.hidden_dim} ** 0.75}

idbd:
  version: squared_grads
  autostep: true
  meta_learning_rate: 0.005
